a: 100
act: xtanh
activation: xtanh
anneal: false
anneal_epoch: 20
b: 1
batch_norm: false
batch_size: 64
c: 0
checkpoint: true
d: 10
dd: 5
dl: 5
epochs: 100
gamma: 0
hidden_dim: 100
ica: true
initialize: true
log: true
lr: 0.01
n_layers: 3
nl: 3
no_scheduler: false
noisy: false
nps: 1000
ns: 40
one_hot: true
p: gauss
s: 1
scheduler_tol: 3
shuffle: true
simple_mixing: false
staircase: false
tcl: false
uncentered: false
